[package]
name = "rush"
version = "0.4.0"
authors = ["Daniel Ackerson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pom = "3.1.0"
unic = "0.9.0"
trees = "0.3.0"
